name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  JAVA_VERSION: '17'
  REGISTRY: docker.io
  IMAGE_NAME: expense-manager

jobs:
  build-test-sonar:
    name: Build, Test (UT+IT), Coverage, Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # SonarCloud needs full history for PRs

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Cache ~/.m2
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Enable Docker (for Testcontainers)
        uses: docker/setup-buildx-action@v3

      - name: Build + tests (JaCoCo)
        run: mvn -B -ntp clean verify -DskipITs=false -DskipTests=false

      # Run SonarCloud scan ONLY if token is provided
      - name: SonarCloud Scan
        if: ${{ secrets.SONAR_TOKEN != '' && secrets.SONAR_ORG != '' && secrets.SONAR_PROJECT_KEY != '' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}                    # e.g. manal-lahmidi  (ORG KEY)
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}    # e.g. Manal-Lahmidi_expense-manager
        run: >
          mvn -B -ntp
          org.sonarsource.scanner.maven:sonar-maven-plugin:5.2.0.4988:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${SONAR_ORG}
          -Dsonar.projectKey=${SONAR_PROJECT_KEY}
          -Dsonar.token=${SONAR_TOKEN}

  docker:
    name: Build & Push Docker image
    needs: build-test-sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
            type=ref,event=branch

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MAVEN_ARGS=-DskipTests

      - name: Show pushed image tags
        run: |
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}"
